### ISSUE TITLE
The released code is not related to the published paper

### ISSUE THREAD

**Issue by Lingzhi-WANG** [JD-AI-Research-NLP/RevCore#2]
I find that the model.py and run.py files are the same as the code in KGSF model. Did you upload the wrong the code?
Also, we cannot download the review data via the link you listed.

Looking forward to your reply.

**Comment by luyulalalala** [comment]
Thanks  for your question first.
Our experiment are majorly based on KGSF, so we have modified some module in the original KGSF,  indeed the file 'model.py' and 'run.py' are KGSF's code.  The modified file are 'model_copy_helpful.py', 'model_copy_random.py', and 'run_train_test_copy.py'. 
Hope it helps.

**Comment by Lingzhi-WANG** [comment]
Thanks for your prompt reply. I got it. 
Maybe you can replace "python run.py" with "python run_train_test_copy.py" in the readme.

BTW, could you share the movie2tokenreview_helpful.pkl with us?
Thank you~
