### ISSUE TITLE
How to get reviews for each movie?

### ISSUE THREAD

**Issue by Lingzhi-WANG** [JD-AI-Research-NLP/RevCore#3]
I'm trying to implement your work by crawling the review data by myself. However, I find that some movies do not have any reviews in IMDB. How do you handle such a situation or just ignore these movies' reviews?

Look forward to your reply.

**Comment by luyulalalala** [comment]
In my practice, the movies without reviews from IMDB were ignored. I also recommend you crawl the wanted reviews from other movie websites besides IMDB.

**Comment by Lingzhi-WANG** [comment]
Thank you for your prompt reply. It helps a lot.
